import { pickWordSet, WORD_LEVEL_LABEL } from './words'

export type KanaEntry = { kana: string; romaji: string[]; translation?: string }
export type KanaType = 'hiragana' | 'katakana' | 'words'
export type Level = 1 | 2 | 3

const HIRAGANA_BASE: KanaEntry[] = [
  { kana: 'あ', romaji: ['a'] },
  { kana: 'い', romaji: ['i'] },
  { kana: 'う', romaji: ['u'] },
  { kana: 'え', romaji: ['e'] },
  { kana: 'お', romaji: ['o'] },
  { kana: 'か', romaji: ['ka'] },
  { kana: 'き', romaji: ['ki'] },
  { kana: 'く', romaji: ['ku'] },
  { kana: 'け', romaji: ['ke'] },
  { kana: 'こ', romaji: ['ko'] },
  { kana: 'さ', romaji: ['sa'] },
  { kana: 'し', romaji: ['shi', 'si'] },
  { kana: 'す', romaji: ['su'] },
  { kana: 'せ', romaji: ['se'] },
  { kana: 'そ', romaji: ['so'] },
  { kana: 'た', romaji: ['ta'] },
  { kana: 'ち', romaji: ['chi', 'ti'] },
  { kana: 'つ', romaji: ['tsu', 'tu'] },
  { kana: 'て', romaji: ['te'] },
  { kana: 'と', romaji: ['to'] },
  { kana: 'な', romaji: ['na'] },
  { kana: 'に', romaji: ['ni'] },
  { kana: 'ぬ', romaji: ['nu'] },
  { kana: 'ね', romaji: ['ne'] },
  { kana: 'の', romaji: ['no'] },
  { kana: 'は', romaji: ['ha'] },
  { kana: 'ひ', romaji: ['hi'] },
  { kana: 'ふ', romaji: ['fu', 'hu'] },
  { kana: 'へ', romaji: ['he'] },
  { kana: 'ほ', romaji: ['ho'] },
  { kana: 'ま', romaji: ['ma'] },
  { kana: 'み', romaji: ['mi'] },
  { kana: 'む', romaji: ['mu'] },
  { kana: 'め', romaji: ['me'] },
  { kana: 'も', romaji: ['mo'] },
  { kana: 'や', romaji: ['ya'] },
  { kana: 'ゆ', romaji: ['yu'] },
  { kana: 'よ', romaji: ['yo'] },
  { kana: 'ら', romaji: ['ra'] },
  { kana: 'り', romaji: ['ri'] },
  { kana: 'る', romaji: ['ru'] },
  { kana: 'れ', romaji: ['re'] },
  { kana: 'ろ', romaji: ['ro'] },
  { kana: 'わ', romaji: ['wa'] },
  { kana: 'を', romaji: ['wo', 'o'] },
  { kana: 'ん', romaji: ['n', 'nn'] },
]

const HIRAGANA_DAKUTEN: KanaEntry[] = [
  { kana: 'が', romaji: ['ga'] },
  { kana: 'ぎ', romaji: ['gi'] },
  { kana: 'ぐ', romaji: ['gu'] },
  { kana: 'げ', romaji: ['ge'] },
  { kana: 'ご', romaji: ['go'] },
  { kana: 'ざ', romaji: ['za'] },
  { kana: 'じ', romaji: ['ji', 'zi'] },
  { kana: 'ず', romaji: ['zu'] },
  { kana: 'ぜ', romaji: ['ze'] },
  { kana: 'ぞ', romaji: ['zo'] },
  { kana: 'だ', romaji: ['da'] },
  { kana: 'ぢ', romaji: ['ji', 'di', 'zi'] },
  { kana: 'づ', romaji: ['zu', 'du'] },
  { kana: 'で', romaji: ['de'] },
  { kana: 'ど', romaji: ['do'] },
  { kana: 'ば', romaji: ['ba'] },
  { kana: 'び', romaji: ['bi'] },
  { kana: 'ぶ', romaji: ['bu'] },
  { kana: 'べ', romaji: ['be'] },
  { kana: 'ぼ', romaji: ['bo'] },
  { kana: 'ぱ', romaji: ['pa'] },
  { kana: 'ぴ', romaji: ['pi'] },
  { kana: 'ぷ', romaji: ['pu'] },
  { kana: 'ぺ', romaji: ['pe'] },
  { kana: 'ぽ', romaji: ['po'] },
]

const HIRAGANA_YOON: KanaEntry[] = [
  { kana: 'きゃ', romaji: ['kya'] },
  { kana: 'きゅ', romaji: ['kyu'] },
  { kana: 'きょ', romaji: ['kyo'] },
  { kana: 'しゃ', romaji: ['sha', 'sya'] },
  { kana: 'しゅ', romaji: ['shu', 'syu'] },
  { kana: 'しょ', romaji: ['sho', 'syo'] },
  { kana: 'ちゃ', romaji: ['cha', 'tya'] },
  { kana: 'ちゅ', romaji: ['chu', 'tyu'] },
  { kana: 'ちょ', romaji: ['cho', 'tyo'] },
  { kana: 'にゃ', romaji: ['nya'] },
  { kana: 'にゅ', romaji: ['nyu'] },
  { kana: 'にょ', romaji: ['nyo'] },
  { kana: 'ひゃ', romaji: ['hya'] },
  { kana: 'ひゅ', romaji: ['hyu'] },
  { kana: 'ひょ', romaji: ['hyo'] },
  { kana: 'みゃ', romaji: ['mya'] },
  { kana: 'みゅ', romaji: ['myu'] },
  { kana: 'みょ', romaji: ['myo'] },
  { kana: 'りゃ', romaji: ['rya'] },
  { kana: 'りゅ', romaji: ['ryu'] },
  { kana: 'りょ', romaji: ['ryo'] },
  { kana: 'ぎゃ', romaji: ['gya'] },
  { kana: 'ぎゅ', romaji: ['gyu'] },
  { kana: 'ぎょ', romaji: ['gyo'] },
  { kana: 'じゃ', romaji: ['ja', 'jya', 'zya'] },
  { kana: 'じゅ', romaji: ['ju', 'jyu', 'zyu'] },
  { kana: 'じょ', romaji: ['jo', 'jyo', 'zyo'] },
  { kana: 'びゃ', romaji: ['bya'] },
  { kana: 'びゅ', romaji: ['byu'] },
  { kana: 'びょ', romaji: ['byo'] },
  { kana: 'ぴゃ', romaji: ['pya'] },
  { kana: 'ぴゅ', romaji: ['pyu'] },
  { kana: 'ぴょ', romaji: ['pyo'] },
]

const KATAKANA_BASE: KanaEntry[] = [
  { kana: 'ア', romaji: ['a'] },
  { kana: 'イ', romaji: ['i'] },
  { kana: 'ウ', romaji: ['u'] },
  { kana: 'エ', romaji: ['e'] },
  { kana: 'オ', romaji: ['o'] },
  { kana: 'カ', romaji: ['ka'] },
  { kana: 'キ', romaji: ['ki'] },
  { kana: 'ク', romaji: ['ku'] },
  { kana: 'ケ', romaji: ['ke'] },
  { kana: 'コ', romaji: ['ko'] },
  { kana: 'サ', romaji: ['sa'] },
  { kana: 'シ', romaji: ['shi', 'si'] },
  { kana: 'ス', romaji: ['su'] },
  { kana: 'セ', romaji: ['se'] },
  { kana: 'ソ', romaji: ['so'] },
  { kana: 'タ', romaji: ['ta'] },
  { kana: 'チ', romaji: ['chi', 'ti'] },
  { kana: 'ツ', romaji: ['tsu', 'tu'] },
  { kana: 'テ', romaji: ['te'] },
  { kana: 'ト', romaji: ['to'] },
  { kana: 'ナ', romaji: ['na'] },
  { kana: 'ニ', romaji: ['ni'] },
  { kana: 'ヌ', romaji: ['nu'] },
  { kana: 'ネ', romaji: ['ne'] },
  { kana: 'ノ', romaji: ['no'] },
  { kana: 'ハ', romaji: ['ha'] },
  { kana: 'ヒ', romaji: ['hi'] },
  { kana: 'フ', romaji: ['fu', 'hu'] },
  { kana: 'ヘ', romaji: ['he'] },
  { kana: 'ホ', romaji: ['ho'] },
  { kana: 'マ', romaji: ['ma'] },
  { kana: 'ミ', romaji: ['mi'] },
  { kana: 'ム', romaji: ['mu'] },
  { kana: 'メ', romaji: ['me'] },
  { kana: 'モ', romaji: ['mo'] },
  { kana: 'ヤ', romaji: ['ya'] },
  { kana: 'ユ', romaji: ['yu'] },
  { kana: 'ヨ', romaji: ['yo'] },
  { kana: 'ラ', romaji: ['ra'] },
  { kana: 'リ', romaji: ['ri'] },
  { kana: 'ル', romaji: ['ru'] },
  { kana: 'レ', romaji: ['re'] },
  { kana: 'ロ', romaji: ['ro'] },
  { kana: 'ワ', romaji: ['wa'] },
  { kana: 'ヲ', romaji: ['wo', 'o'] },
  { kana: 'ン', romaji: ['n', 'nn'] },
]

const KATAKANA_DAKUTEN: KanaEntry[] = [
  { kana: 'ガ', romaji: ['ga'] },
  { kana: 'ギ', romaji: ['gi'] },
  { kana: 'グ', romaji: ['gu'] },
  { kana: 'ゲ', romaji: ['ge'] },
  { kana: 'ゴ', romaji: ['go'] },
  { kana: 'ザ', romaji: ['za'] },
  { kana: 'ジ', romaji: ['ji', 'zi'] },
  { kana: 'ズ', romaji: ['zu'] },
  { kana: 'ゼ', romaji: ['ze'] },
  { kana: 'ゾ', romaji: ['zo'] },
  { kana: 'ダ', romaji: ['da'] },
  { kana: 'ヂ', romaji: ['ji', 'di', 'zi'] },
  { kana: 'ヅ', romaji: ['zu', 'du'] },
  { kana: 'デ', romaji: ['de'] },
  { kana: 'ド', romaji: ['do'] },
  { kana: 'バ', romaji: ['ba'] },
  { kana: 'ビ', romaji: ['bi'] },
  { kana: 'ブ', romaji: ['bu'] },
  { kana: 'ベ', romaji: ['be'] },
  { kana: 'ボ', romaji: ['bo'] },
  { kana: 'パ', romaji: ['pa'] },
  { kana: 'ピ', romaji: ['pi'] },
  { kana: 'プ', romaji: ['pu'] },
  { kana: 'ペ', romaji: ['pe'] },
  { kana: 'ポ', romaji: ['po'] },
]

const KATAKANA_YOON: KanaEntry[] = [
  { kana: 'キャ', romaji: ['kya'] },
  { kana: 'キュ', romaji: ['kyu'] },
  { kana: 'キョ', romaji: ['kyo'] },
  { kana: 'シャ', romaji: ['sha', 'sya'] },
  { kana: 'シュ', romaji: ['shu', 'syu'] },
  { kana: 'ショ', romaji: ['sho', 'syo'] },
  { kana: 'チャ', romaji: ['cha', 'tya'] },
  { kana: 'チュ', romaji: ['chu', 'tyu'] },
  { kana: 'チョ', romaji: ['cho', 'tyo'] },
  { kana: 'ニャ', romaji: ['nya'] },
  { kana: 'ニュ', romaji: ['nyu'] },
  { kana: 'ニョ', romaji: ['nyo'] },
  { kana: 'ヒャ', romaji: ['hya'] },
  { kana: 'ヒュ', romaji: ['hyu'] },
  { kana: 'ヒョ', romaji: ['hyo'] },
  { kana: 'ミャ', romaji: ['mya'] },
  { kana: 'ミュ', romaji: ['myu'] },
  { kana: 'ミョ', romaji: ['myo'] },
  { kana: 'リャ', romaji: ['rya'] },
  { kana: 'リュ', romaji: ['ryu'] },
  { kana: 'リョ', romaji: ['ryo'] },
  { kana: 'ギャ', romaji: ['gya'] },
  { kana: 'ギュ', romaji: ['gyu'] },
  { kana: 'ギョ', romaji: ['gyo'] },
  { kana: 'ジャ', romaji: ['ja', 'jya', 'zya'] },
  { kana: 'ジュ', romaji: ['ju', 'jyu', 'zyu'] },
  { kana: 'ジョ', romaji: ['jo', 'jyo', 'zyo'] },
  { kana: 'ビャ', romaji: ['bya'] },
  { kana: 'ビュ', romaji: ['byu'] },
  { kana: 'ビョ', romaji: ['byo'] },
  { kana: 'ピャ', romaji: ['pya'] },
  { kana: 'ピュ', romaji: ['pyu'] },
  { kana: 'ピョ', romaji: ['pyo'] },
]

export function pickSet(type: KanaType, level: Level): KanaEntry[] {
  if (type === 'words') {
    // Imported lazily to avoid a circular import at the top of the file.
    return pickWordSet(level)
  }
  if (type === 'hiragana') {
    if (level === 1) return HIRAGANA_BASE
    if (level === 2) return [...HIRAGANA_BASE, ...HIRAGANA_DAKUTEN]
    return [...HIRAGANA_BASE, ...HIRAGANA_DAKUTEN, ...HIRAGANA_YOON]
  }
  if (level === 1) return KATAKANA_BASE
  if (level === 2) return [...KATAKANA_BASE, ...KATAKANA_DAKUTEN]
  return [...KATAKANA_BASE, ...KATAKANA_DAKUTEN, ...KATAKANA_YOON]
}

export const LEVEL_LABEL: Record<Level, string> = {
  1: 'Gojūon',
  2: '+ Dakuten',
  3: '+ Yōon',
}

export function levelLabel(type: KanaType, level: Level): string {
  if (type === 'words') return WORD_LEVEL_LABEL[level]
  return LEVEL_LABEL[level]
}
