import type { KanaEntry } from './kana'

export type WordEntry = KanaEntry & { translation: string }

const GREETINGS: WordEntry[] = [
  { kana: 'こんにちは', romaji: ['konnichiwa'], translation: 'hello / good afternoon' },
  { kana: 'おはよう', romaji: ['ohayou', 'ohayo'], translation: 'good morning' },
  { kana: 'こんばんは', romaji: ['konbanwa'], translation: 'good evening' },
  { kana: 'おやすみ', romaji: ['oyasumi'], translation: 'good night' },
  { kana: 'さようなら', romaji: ['sayounara', 'sayonara'], translation: 'goodbye' },
  { kana: 'またね', romaji: ['matane'], translation: 'see you' },
  { kana: 'ありがとう', romaji: ['arigatou', 'arigato'], translation: 'thank you' },
  { kana: 'どうも', romaji: ['doumo', 'domo'], translation: 'thanks (informal)' },
  { kana: 'すみません', romaji: ['sumimasen'], translation: 'excuse me / sorry' },
  { kana: 'ごめんなさい', romaji: ['gomennasai'], translation: "I'm sorry" },
  { kana: 'ごめん', romaji: ['gomen'], translation: 'sorry' },
  { kana: 'はじめまして', romaji: ['hajimemashite'], translation: 'nice to meet you' },
  { kana: 'よろしく', romaji: ['yoroshiku', 'yorosiku'], translation: 'pleased to meet you' },
  { kana: 'はい', romaji: ['hai'], translation: 'yes' },
  { kana: 'いいえ', romaji: ['iie'], translation: 'no' },
  { kana: 'どうぞ', romaji: ['douzo', 'dozo'], translation: 'please / go ahead' },
  { kana: 'おめでとう', romaji: ['omedetou', 'omedeto'], translation: 'congratulations' },
  { kana: 'がんばって', romaji: ['ganbatte'], translation: 'do your best' },
  { kana: 'いただきます', romaji: ['itadakimasu'], translation: 'thanks for the meal (before)' },
  { kana: 'ごちそうさま', romaji: ['gochisousama', 'gochisosama'], translation: 'thanks for the meal (after)' },
  { kana: 'おかえり', romaji: ['okaeri'], translation: 'welcome back' },
  { kana: 'ただいま', romaji: ['tadaima'], translation: "I'm home" },
  { kana: 'いってきます', romaji: ['ittekimasu'], translation: 'I am going (out)' },
  { kana: 'いってらっしゃい', romaji: ['itterasshai'], translation: 'have a good trip' },
  { kana: 'おねがい', romaji: ['onegai'], translation: 'please / I beg you' },
  { kana: 'だいじょうぶ', romaji: ['daijoubu', 'daijobu'], translation: "it's okay" },
  { kana: 'おつかれさま', romaji: ['otsukaresama', 'otukaresama'], translation: 'good work' },
]

const COMMON_NOUNS: WordEntry[] = [
  { kana: 'ねこ', romaji: ['neko'], translation: 'cat' },
  { kana: 'いぬ', romaji: ['inu'], translation: 'dog' },
  { kana: 'とり', romaji: ['tori'], translation: 'bird' },
  { kana: 'さかな', romaji: ['sakana'], translation: 'fish' },
  { kana: 'うま', romaji: ['uma'], translation: 'horse' },
  { kana: 'うさぎ', romaji: ['usagi'], translation: 'rabbit' },
  { kana: 'くま', romaji: ['kuma'], translation: 'bear' },
  { kana: 'むし', romaji: ['mushi', 'musi'], translation: 'insect' },
  { kana: 'りんご', romaji: ['ringo'], translation: 'apple' },
  { kana: 'みかん', romaji: ['mikan'], translation: 'mandarin' },
  { kana: 'いちご', romaji: ['ichigo', 'itigo'], translation: 'strawberry' },
  { kana: 'ぶどう', romaji: ['budou', 'budo'], translation: 'grape' },
  { kana: 'もも', romaji: ['momo'], translation: 'peach' },
  { kana: 'すいか', romaji: ['suika'], translation: 'watermelon' },
  { kana: 'やさい', romaji: ['yasai'], translation: 'vegetable' },
  { kana: 'にく', romaji: ['niku'], translation: 'meat' },
  { kana: 'たまご', romaji: ['tamago'], translation: 'egg' },
  { kana: 'こめ', romaji: ['kome'], translation: 'rice (raw)' },
  { kana: 'ごはん', romaji: ['gohan'], translation: 'rice / meal' },
  { kana: 'みず', romaji: ['mizu'], translation: 'water' },
  { kana: 'おちゃ', romaji: ['ocha', 'otya'], translation: 'tea' },
  { kana: 'のみもの', romaji: ['nomimono'], translation: 'drink' },
  { kana: 'たべもの', romaji: ['tabemono'], translation: 'food' },
  { kana: 'やま', romaji: ['yama'], translation: 'mountain' },
  { kana: 'かわ', romaji: ['kawa'], translation: 'river' },
  { kana: 'うみ', romaji: ['umi'], translation: 'sea' },
  { kana: 'そら', romaji: ['sora'], translation: 'sky' },
  { kana: 'つき', romaji: ['tsuki', 'tuki'], translation: 'moon' },
  { kana: 'ひ', romaji: ['hi'], translation: 'sun / fire / day' },
  { kana: 'ほし', romaji: ['hoshi', 'hosi'], translation: 'star' },
  { kana: 'き', romaji: ['ki'], translation: 'tree' },
  { kana: 'はな', romaji: ['hana'], translation: 'flower / nose' },
  { kana: 'みち', romaji: ['michi', 'miti'], translation: 'road' },
  { kana: 'いえ', romaji: ['ie'], translation: 'house' },
  { kana: 'へや', romaji: ['heya'], translation: 'room' },
  { kana: 'まど', romaji: ['mado'], translation: 'window' },
  { kana: 'いす', romaji: ['isu'], translation: 'chair' },
  { kana: 'つくえ', romaji: ['tsukue', 'tukue'], translation: 'desk' },
  { kana: 'ほん', romaji: ['hon'], translation: 'book' },
  { kana: 'えんぴつ', romaji: ['enpitsu', 'enpitu'], translation: 'pencil' },
  { kana: 'かみ', romaji: ['kami'], translation: 'paper / hair' },
  { kana: 'がっこう', romaji: ['gakkou', 'gakko'], translation: 'school' },
  { kana: 'だいがく', romaji: ['daigaku'], translation: 'university' },
  { kana: 'きょうしつ', romaji: ['kyoushitsu', 'kyositu', 'kyoshitsu'], translation: 'classroom' },
  { kana: 'せんせい', romaji: ['sensei'], translation: 'teacher' },
  { kana: 'がくせい', romaji: ['gakusei'], translation: 'student' },
  { kana: 'ともだち', romaji: ['tomodachi', 'tomodati'], translation: 'friend' },
  { kana: 'かぞく', romaji: ['kazoku'], translation: 'family' },
  { kana: 'おかあさん', romaji: ['okaasan', 'okasan'], translation: 'mother' },
  { kana: 'おとうさん', romaji: ['otousan', 'otosan'], translation: 'father' },
  { kana: 'あに', romaji: ['ani'], translation: 'older brother' },
  { kana: 'あね', romaji: ['ane'], translation: 'older sister' },
  { kana: 'おとうと', romaji: ['otouto', 'ototo'], translation: 'younger brother' },
  { kana: 'いもうと', romaji: ['imouto', 'imoto'], translation: 'younger sister' },
  { kana: 'こども', romaji: ['kodomo'], translation: 'child' },
  { kana: 'ひと', romaji: ['hito'], translation: 'person' },
  { kana: 'おとな', romaji: ['otona'], translation: 'adult' },
  { kana: 'おとこ', romaji: ['otoko'], translation: 'man' },
  { kana: 'おんな', romaji: ['onna'], translation: 'woman' },
  { kana: 'くるま', romaji: ['kuruma'], translation: 'car' },
  { kana: 'でんしゃ', romaji: ['densha', 'densya'], translation: 'train' },
  { kana: 'ひこうき', romaji: ['hikouki', 'hikoki'], translation: 'airplane' },
  { kana: 'じてんしゃ', romaji: ['jitensha', 'jitensya', 'zitensya'], translation: 'bicycle' },
  { kana: 'ふね', romaji: ['fune', 'hune'], translation: 'ship / boat' },
  { kana: 'えき', romaji: ['eki'], translation: 'station' },
  { kana: 'まち', romaji: ['machi', 'mati'], translation: 'town' },
  { kana: 'にほん', romaji: ['nihon', 'nippon'], translation: 'Japan' },
  { kana: 'しごと', romaji: ['shigoto', 'sigoto'], translation: 'work / job' },
  { kana: 'でんわ', romaji: ['denwa'], translation: 'phone' },
  { kana: 'おかね', romaji: ['okane'], translation: 'money' },
  { kana: 'なまえ', romaji: ['namae'], translation: 'name' },
  { kana: 'かばん', romaji: ['kaban'], translation: 'bag' },
  { kana: 'とけい', romaji: ['tokei'], translation: 'clock / watch' },
  { kana: 'てがみ', romaji: ['tegami'], translation: 'letter' },
  { kana: 'しんぶん', romaji: ['shinbun', 'sinbun'], translation: 'newspaper' },
  { kana: 'えいが', romaji: ['eiga'], translation: 'movie' },
  { kana: 'おんがく', romaji: ['ongaku'], translation: 'music' },
  { kana: 'うた', romaji: ['uta'], translation: 'song' },
]

const VERBS_AND_ADJECTIVES: WordEntry[] = [
  { kana: 'たべる', romaji: ['taberu'], translation: 'to eat' },
  { kana: 'のむ', romaji: ['nomu'], translation: 'to drink' },
  { kana: 'みる', romaji: ['miru'], translation: 'to see / watch' },
  { kana: 'きく', romaji: ['kiku'], translation: 'to listen / ask' },
  { kana: 'いく', romaji: ['iku'], translation: 'to go' },
  { kana: 'くる', romaji: ['kuru'], translation: 'to come' },
  { kana: 'かえる', romaji: ['kaeru'], translation: 'to return' },
  { kana: 'する', romaji: ['suru'], translation: 'to do' },
  { kana: 'なる', romaji: ['naru'], translation: 'to become' },
  { kana: 'ある', romaji: ['aru'], translation: 'to be (objects)' },
  { kana: 'いる', romaji: ['iru'], translation: 'to be (people)' },
  { kana: 'もつ', romaji: ['motsu', 'motu'], translation: 'to hold' },
  { kana: 'かう', romaji: ['kau'], translation: 'to buy' },
  { kana: 'うる', romaji: ['uru'], translation: 'to sell' },
  { kana: 'つくる', romaji: ['tsukuru', 'tukuru'], translation: 'to make' },
  { kana: 'はじめる', romaji: ['hajimeru', 'hazimeru'], translation: 'to begin' },
  { kana: 'おわる', romaji: ['owaru'], translation: 'to end' },
  { kana: 'つかう', romaji: ['tsukau', 'tukau'], translation: 'to use' },
  { kana: 'できる', romaji: ['dekiru'], translation: 'can do' },
  { kana: 'わかる', romaji: ['wakaru'], translation: 'to understand' },
  { kana: 'しる', romaji: ['shiru', 'siru'], translation: 'to know' },
  { kana: 'おぼえる', romaji: ['oboeru'], translation: 'to remember' },
  { kana: 'わすれる', romaji: ['wasureru'], translation: 'to forget' },
  { kana: 'おもう', romaji: ['omou'], translation: 'to think / feel' },
  { kana: 'はなす', romaji: ['hanasu'], translation: 'to speak' },
  { kana: 'いう', romaji: ['iu'], translation: 'to say' },
  { kana: 'よむ', romaji: ['yomu'], translation: 'to read' },
  { kana: 'かく', romaji: ['kaku'], translation: 'to write' },
  { kana: 'ねる', romaji: ['neru'], translation: 'to sleep' },
  { kana: 'おきる', romaji: ['okiru'], translation: 'to wake up' },
  { kana: 'たつ', romaji: ['tatsu', 'tatu'], translation: 'to stand' },
  { kana: 'すわる', romaji: ['suwaru'], translation: 'to sit' },
  { kana: 'あるく', romaji: ['aruku'], translation: 'to walk' },
  { kana: 'はしる', romaji: ['hashiru', 'hasiru'], translation: 'to run' },
  { kana: 'およぐ', romaji: ['oyogu'], translation: 'to swim' },
  { kana: 'とぶ', romaji: ['tobu'], translation: 'to fly / jump' },
  { kana: 'なく', romaji: ['naku'], translation: 'to cry' },
  { kana: 'わらう', romaji: ['warau'], translation: 'to laugh' },
  { kana: 'あう', romaji: ['au'], translation: 'to meet' },
  { kana: 'まつ', romaji: ['matsu', 'matu'], translation: 'to wait' },
  { kana: 'あける', romaji: ['akeru'], translation: 'to open' },
  { kana: 'しめる', romaji: ['shimeru', 'simeru'], translation: 'to close' },
  { kana: 'とまる', romaji: ['tomaru'], translation: 'to stop' },
  { kana: 'はたらく', romaji: ['hataraku'], translation: 'to work' },
  { kana: 'べんきょう', romaji: ['benkyou', 'benkyo'], translation: 'study' },
  { kana: 'りょこう', romaji: ['ryokou', 'ryoko'], translation: 'travel' },
  { kana: 'おおきい', romaji: ['ookii', 'ooki', 'okii'], translation: 'big' },
  { kana: 'ちいさい', romaji: ['chiisai', 'chisai', 'tiisai'], translation: 'small' },
  { kana: 'たかい', romaji: ['takai'], translation: 'tall / expensive' },
  { kana: 'ひくい', romaji: ['hikui'], translation: 'low / short' },
  { kana: 'ながい', romaji: ['nagai'], translation: 'long' },
  { kana: 'みじかい', romaji: ['mijikai', 'mizikai'], translation: 'short' },
  { kana: 'はやい', romaji: ['hayai'], translation: 'fast / early' },
  { kana: 'おそい', romaji: ['osoi'], translation: 'slow / late' },
  { kana: 'あつい', romaji: ['atsui', 'atui'], translation: 'hot' },
  { kana: 'さむい', romaji: ['samui'], translation: 'cold (weather)' },
  { kana: 'つめたい', romaji: ['tsumetai', 'tumetai'], translation: 'cold (touch)' },
  { kana: 'あたたかい', romaji: ['atatakai'], translation: 'warm' },
  { kana: 'あかるい', romaji: ['akarui'], translation: 'bright' },
  { kana: 'くらい', romaji: ['kurai'], translation: 'dark' },
  { kana: 'あまい', romaji: ['amai'], translation: 'sweet' },
  { kana: 'からい', romaji: ['karai'], translation: 'spicy' },
  { kana: 'おいしい', romaji: ['oishii', 'oishi', 'oisii'], translation: 'delicious' },
  { kana: 'おもい', romaji: ['omoi'], translation: 'heavy' },
  { kana: 'かるい', romaji: ['karui'], translation: 'light (weight)' },
  { kana: 'あたらしい', romaji: ['atarashii', 'atarashi'], translation: 'new' },
  { kana: 'ふるい', romaji: ['furui', 'hurui'], translation: 'old (object)' },
  { kana: 'いい', romaji: ['ii'], translation: 'good' },
  { kana: 'わるい', romaji: ['warui'], translation: 'bad' },
  { kana: 'たのしい', romaji: ['tanoshii', 'tanoshi', 'tanosii'], translation: 'fun' },
  { kana: 'うれしい', romaji: ['ureshii', 'ureshi', 'uresii'], translation: 'happy' },
  { kana: 'かなしい', romaji: ['kanashii', 'kanashi', 'kanasii'], translation: 'sad' },
  { kana: 'いそがしい', romaji: ['isogashii', 'isogashi', 'isogasii'], translation: 'busy' },
  { kana: 'やすい', romaji: ['yasui'], translation: 'cheap' },
  { kana: 'むずかしい', romaji: ['muzukashii', 'muzukashi', 'muzukasii'], translation: 'difficult' },
  { kana: 'やさしい', romaji: ['yasashii', 'yasashi', 'yasasii'], translation: 'kind / easy' },
  { kana: 'ちかい', romaji: ['chikai', 'tikai'], translation: 'near' },
  { kana: 'とおい', romaji: ['tooi', 'toi'], translation: 'far' },
  { kana: 'ひろい', romaji: ['hiroi'], translation: 'wide' },
  { kana: 'せまい', romaji: ['semai'], translation: 'narrow' },
  { kana: 'きれい', romaji: ['kirei'], translation: 'pretty / clean' },
  { kana: 'かわいい', romaji: ['kawaii', 'kawai'], translation: 'cute' },
  { kana: 'つよい', romaji: ['tsuyoi', 'tuyoi'], translation: 'strong' },
  { kana: 'よわい', romaji: ['yowai'], translation: 'weak' },
]

import type { Level } from './kana'

export function pickWordSet(level: Level): WordEntry[] {
  if (level === 1) return GREETINGS
  if (level === 2) return [...GREETINGS, ...COMMON_NOUNS]
  return [...GREETINGS, ...COMMON_NOUNS, ...VERBS_AND_ADJECTIVES]
}

export const WORD_LEVEL_LABEL: Record<Level, string> = {
  1: 'Greetings',
  2: '+ Nouns',
  3: '+ Verbs',
}
